### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [gifrancohe/react-firebase#1]
hi @gifrancohe  Good day! I an a graphics artist and i would like to contribute to your project by designing a logo for it. If you are interested i will begin my design asap. Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by gifrancohe** [comment]
Hi @Tobaloidee,

Thank you very much for your proposal, but this is just a test project, in case I have a real project I will not hesitate to contact you
